#!/bin/bash -e

# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


#buildAll push docker-sandbox.infra.cloudera.com/hive/hive-dev-box


set -x
d="`date +%Y%m%d%H%M%S`"

push="echo NOT pushing"
if [ "$1" == "push" ]; then
	push="docker push"
	shift
fi


baseName=apache/hive-dev-box
altName=apache/hive-dev-box
if [ "$1" != "" ]; then
	altName="$1"
	shift
fi

function build() {
	n="$1"
	shift
	docker build -t  $baseName:${n} \
		      -t $baseName:${n}-$d	"$@"
	docker tag $baseName:${n} $altName:${n}
	docker tag $baseName:${n} $altName:${n}-$d

	$push $altName:${n}
	$push $altName:${n}-$d
}

build latest		-f Dockerfile .
build executor		-f Dockerfile.executor .
build executor-1001	-f Dockerfile.executor --build-arg UID=1001 .
build bazaar		-f Dockerfile.bazaar .

