#!/bin/bash -e

# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# File needs to be called /hooks/build relative to the Dockerfile.
# $IMAGE_NAME var is injected into the build so the tag is correct.

echo "[@] hooks/build"
set

BUILD_ARGS="build"
if [ "$DOCKER_TAG" == "executor-1001" ];then
	BUILD_ARGS+=" --build-arg UID=1001"
fi
BUILD_ARGS+=" -f $DOCKERFILE_PATH -t $IMAGE_NAME ."

set -x
docker $BUILD_ARGS
