#!/bin/bash -e

# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# FIXME: consider setting
#Set hive.tez.container.size=3356;
#Set hive.tez.java.opts=-Xmx2g;
#conf set hive/hive-site hive.tez.container.size 3356
#conf set hive/hive-site hive.tez.java.opts -Xmx2g
# FIXME: scale up mem values?

#addgroup --gid 999 docker_access
#adduser dev docker_access

cd tmp
#apt-get install -y dnsutils wmctrl firefox-esr

cat >> ~dev/.bashrc << EOF
export HIVE_TEST_DOCKER_HOST="\`ip r | grep '^default'|cut -d ' ' -f 3\`"

[ -d /hive-dev-box/ ] && . /hive-dev-box/bashrc

if [ "\$DISPLAY" != "" ]; then
  export WID=\`xprop -root _NET_ACTIVE_WINDOW|cut -d ' ' -f5\`
fi

function urgent() { wmctrl -i -r \$WID   -b add,demands_attention; backburner \$HOSTNAME;}

EOF


/tools/build_cleanup
