#!/bin/bash

# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -e

UID=${1:-1000}

userdel dev
groupadd -g $UID jenkins
useradd -m -o -u $UID -g $UID -d /home/jenkins -s /bin/bash jenkins

echo 'jenkins:jenkins' | chpasswd

cat >> /etc/sudoers << EOF
jenkins ALL=(ALL) NOPASSWD:ALL
EOF


cat >> ~jenkins/.bashrc << EOF

alias grep='grep --color=auto'
alias Grep=grep
export USER=jenkins

EOF

apt-get install -y rsync python

/tools/build_cleanup
