#!/bin/bash -e

# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

sudo apt-get install -y cmake  libssl-dev \
	krb5-multidev libkrb5-dev gdb \
		 libreadline-dev libz-dev bison flex bear ninja-build meson libipc-run-perl iproute2 gitsome clang-format-13


#export DEBUGINFOD_URLS="https://debuginfod.debian.net"

#sudo mkdir /usr/local/pg
#sudo chown dev /usr/local/pg
/tools/build_cleanup
#deb http://apt.llvm.org/bullseye/ llvm-toolchain-bullseye main
